spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/budget-tracker}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    # show-sql: ${SPRING_JPA_SHOW_SQL}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    defer-datasource-initialization: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true # Ensures Flyway checks for inconsistencies

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never
    include-path: never
  compression:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    enabled: true

logging:
  level:
    root: debug
  file:
    name: logs/nexuspro-erm.log

cache:
  type: caffeine
  caffeine:
    spec: maximumSize=500,expireAfterWrite=600s

websocket:
  endpoint: /ws
  allowed-origins: http://localhost:3000

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION}
      refresh-token.expiration: ${APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION}
