server:
  port: 8001
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget-tracker
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # Changed from create-drop to update
    show-sql: true
    open-in-view: false # Disabled to avoid warnings

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO

  file:
    name: logs/nexuspro-erm.log

cache:
  type: caffeine
  caffeine:
    spec: maximumSize=500,expireAfterWrite=600s

websocket:
  endpoint: /ws
  allowed-origins: http://localhost:3000

application:
  security:
    jwt:
      secret-key: M+TYutS09GvjyRQuJYqod6QJnCk6tmH5VeDUjuXy8Pp2cQFuzfRdvNQMYYKvN0y3Wqjzb1YYJofJi38xiWKbTr+w/upaH6uEVv8bQaThSGrR1NMHpPsIk07rZK9nJTEGKjJCLOc9VbplPIqcVkxzJYHOImYK2XE2p0Jbf8ZL7P2Fn95DmgGTNLMl5Wj100jLyWLOUWlE4oPYAm3I6tL0zLsllFgfC7SuU7pms+R8eEgj+JVdQZJ0dvCLnU7yYlsQkcglcabo/ZvNKJzNHC/NT1CxQQeRPiWBgjF36d5h/47C9Pm+oX9HU2wbyrm32tIkWM/WOUwBWqFN3+A04NTAmEQ517CFob7B6L9kb/mcP+A=
      expiration: 36000000000000
      refresh-token.expiration: 86400
